# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20160806_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='time',
        ),
    ]
